<a href="https://colab.research.google.com/github/aks3213/009_AkshayBhanderi/blob/main/Lab_05_task2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Task2: Try Linear regression on same prediction data using Tensorflow

In [1]:
#importing modules
import numpy as np
import tensorflow as tf

In [2]:
inputs = np.array([[73, 67, 43], 
              [91, 88, 64], 
              [87, 134, 58], 
              [102, 43, 37], 
              [69, 96, 70]], dtype='float64')

targets = np.array([[56],[81],[119], [22],  [103]], dtype='float64')

In [3]:
inputs = tf.Variable(inputs)
targets = tf.Variable(targets)
print("targets :\n",targets)

targets :
 <tf.Variable 'Variable:0' shape=(5, 1) dtype=float64, numpy=
array([[ 56.],
       [ 81.],
       [119.],
       [ 22.],
       [103.]])>


In [4]:
v = np.random.rand(3,2)
r = np.random.randn(2)
v = tf.Variable(v)
r = tf.Variable(r)

print(v)
print("\n",r)

<tf.Variable 'Variable:0' shape=(3, 2) dtype=float64, numpy=
array([[0.23890571, 0.88716575],
       [0.7864327 , 0.40382562],
       [0.47197161, 0.30813443]])>

 <tf.Variable 'Variable:0' shape=(2,) dtype=float64, numpy=array([-0.1493077 ,  0.07611572])>


In [5]:
def model(s):
    return s @ v + r

In [6]:
prediction = model(inputs)
print(prediction)

tf.Tensor(
[[ 90.27657959 105.14531197]
 [121.00337293 136.06545635]
 [153.39182473 149.24396521]
 [ 75.49863083 119.33249721]
 [124.87073846 121.62722145]], shape=(5, 2), dtype=float64)


In [7]:
def mse(t1,t2):
    return tf.reduce_mean(tf.square(t1 - t2))
print(mse(prediction,targets))

tf.Tensor(2348.113606003809, shape=(), dtype=float64)


In [8]:
epochs = 40
for epoch_count in range(epochs):
    
    with tf.GradientTape(persistent=True) as t:
        current_loss = mse(targets, model(inputs))

    v1 = t.gradient(current_loss,v)
    r1 = t.gradient(current_loss,r)

    v.assign_sub(1e-4 * v1)
    r.assign_sub(1e-4 * r1)
        
    print(f" \n Epoch count: {epoch_count} \n Loss value: {current_loss.numpy()}")


 
 Epoch count: 0 
 Loss value: 2348.113606003809
 
 Epoch count: 1 
 Loss value: 1630.1135313779753
 
 Epoch count: 2 
 Loss value: 1161.7580967378437
 
 Epoch count: 3 
 Loss value: 851.9216378380837
 
 Epoch count: 4 
 Loss value: 643.309176420749
 
 Epoch count: 5 
 Loss value: 499.8252925286721
 
 Epoch count: 6 
 Loss value: 398.66782195778535
 
 Epoch count: 7 
 Loss value: 325.37791521597194
 
 Epoch count: 8 
 Loss value: 270.7400492492988
 
 Epoch count: 9 
 Loss value: 228.83977004973272
 
 Epoch count: 10 
 Loss value: 195.84606488406993
 
 Epoch count: 11 
 Loss value: 169.24737384272768
 
 Epoch count: 12 
 Loss value: 147.37167175554904
 
 Epoch count: 13 
 Loss value: 129.08450503351855
 
 Epoch count: 14 
 Loss value: 113.5985684015066
 
 Epoch count: 15 
 Loss value: 100.35324653768384
 
 Epoch count: 16 
 Loss value: 88.93808866096549
 
 Epoch count: 17 
 Loss value: 79.04391056092757
 
 Epoch count: 18 
 Loss value: 70.43130584995107
 
 Epoch count: 19 
 Loss value: